// <auto-generated />
namespace MVCAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class name_required1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(name_required1));
        
        string IMigrationMetadata.Id
        {
            get { return "201904110353319_name_required1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
